worker:
  replicas: 0
  env:
    - name: EXTRA_PIP_PACKAGES
      value: >-
        sklearn
        scipy
        gensim
        pyyaml
        dask-ml
        dask-searchcv
    - name: EXTRA_CONDA_PACKAGES
      value: >-
        xgboost
        -c conda-forge
  limits:
    cpu: 1
    memory: 6G

workers:
  default_resources:
    cpu: 1
    memory: 6G

jupyter:
  env:
    - name: EXTRA_PIP_PACKAGES
      value: >-
        sklearn
        scipy
        gensim
        pyyaml
        dask-ml
        dask-searchcv
    - name: EXTRA_CONDA_PACKAGES
      value: >-
        xgboost
  limits:
    cpu: 3
    memory: 20G
