# nameOverride: dask
# fullnameOverride: dask

scheduler:
  name: scheduler
  image:
    repository: "daskdev/dask"
    tag: "0.17.1"
    pullPolicy: IfNotPresent
  replicas: 1
  nodeSelector:
    cloud.google.com/gke-nodepool: dask-cluster-np-scheduler
  serviceType: LoadBalancer
  servicePort: 8786
  resources:
    limits:
      cpu: 1
      memory: 3.5G

webUI:
  name: webui
  servicePort: 80

worker:
  name: worker
  image:
    repository: "daskdev/dask"
    tag: "0.17.1"
    pullPolicy: IfNotPresent
  replicas: 6
  nodeSelector:
    cloud.google.com/gke-nodepool: dask-cluster-np-workers
  aptPackages: >-
  env:
    - name: EXTRA_PIP_PACKAGES
      value: >-
        sklearn
        scipy
        gensim
        pyyaml
        dask-ml
        dask-searchcv
    - name: EXTRA_CONDA_PACKAGES
      value: >-
        xgboost
        -c conda-forge
  resources:
    limits:
      cpu: 1
      memory: 3.5G

jupyter:
  name: jupyter
  enabled: true
  image:
    repository: "daskdev/dask-notebook"
    tag: "0.17.1"
    pullPolicy: IfNotPresent
  replicas: 1
  nodeSelector:
    cloud.google.com/gke-nodepool: dask-cluster-np-scheduler
  serviceType: LoadBalancer
  servicePort: 80
  password: 'sha1:aae8550c0a44:9507d45e087d5ee481a5ce9f4f16f37a0867318c'  # 'dask'
  env:
    - name: EXTRA_PIP_PACKAGES
      value: >-
        sklearn
        scipy
        gensim
        pyyaml
        dask-ml
        dask-searchcv
        google-cloud-storage
    - name: EXTRA_CONDA_PACKAGES
      value: >-
        xgboost
  resources:
    limits:
      cpu: 1
      memory: 3.5G
