worker:
  replicas: 8
  env:
    - name: EXTRA_PIP_PACKAGES
      value: >-
        sklearn
        scipy
        gensim
        pyyaml
        dask-ml
        dask-searchcv
    - name: EXTRA_CONDA_PACKAGES
      value: >-
        xgboost
        -c conda-forge
  limits:
    cpu: 1
    memory: 3.5G

workers:
  default_resources:
    cpu: 1
    memory: 3.5G

jupyter:
  env:
    - name: EXTRA_PIP_PACKAGES
      value: >-
        sklearn
        scipy
        gensim
        pyyaml
        dask-ml
        dask-searchcv
        google-cloud-storage
    - name: EXTRA_CONDA_PACKAGES
      value: >-
        xgboost
  limits:
    cpu: 2
    memory: 7G
